Iteration:

Is the ability to run one or more statments mutliple times. This feature is referred to as iterration on looping. 
There are two ways to do this in python using  (For, While loops)
we consider the Iterations as extension of (If statment)?

1. While Loop

while condition:  i<=3

    statment(s)

In [93]:
# Calculating the factorial of a number  
fact=1              
i=1

while i <= 10:                           #As the condition still true the loop continue iterating 
    fact= fact * i
    i=i+1                                
print("factorial of 10 is: {}".format(fact))

factorial of 10 is: 3628800

#Infinte loop 
fact=1              
i=1

while i > 0:                           #wrong condition
    fact *=  i
    i += 1 
    print(i)

#Calculating the factorial of a number 
fact=1              
i=1

while i <= 10:                     
    fact= fact * i                      # forget increament (i) will not change

Q\ Make a code that finds the student index in a list of names.

In [102]:
A406=['Aya','Nada', 'Yahia', 'Y.M', 'Y.S','M.G','Abanob','Omar']              
i=0
while i <= 7:                           
    if "Abanob" in A406[i]:
        print("The index of the new regestered student is: {}".format(i))
        break
    i = i+1 
#print("We finished this class")

The index of the new regestered student is: 6

For Loop:

Is used to iterate the loop over sequences (Lists, tuples, dictionary, strings and ranges)
The statments of the for loop are excuted once for each element in sequence.

for value in sequance:

    statment(s)

In [2]:
#looping over a list or Tuple

days=['Saturday', 'Sun', 'Monday', 'Tuesday', 'wednes', 'Thursday', 'Friday']

for i in days:
    print(i)

Saturday
Sun
Monday
Tuesday
wednes
Thursday
Friday

In [12]:
# Append function
weekends=[]
working_days=[]

for i in range (len(days)):
    if 'Saturday' in days[i]:
        weekends.append(days[i])     
    elif 'Friday' in days[i]:
        weekends.append(days[i])
    else :
        working_days.append(days[i])
        
print("weekends are {}:".format(weekends))
print("working days are {}:".format(working_days))

weekends are ['Saturday', 'Friday']:
working days are ['Sun', 'Monday', 'Tuesday', 'wednes', 'Thursday']:

In [107]:
#looping over a string

today ='Monday'

for i in today:
    print(i)

M
o
n
d
a
y

In [108]:
#looping over a dictionary
first_year ={'Names':['Salma','Islam','Mohamad',"Nour"] , "Age":17, "subjects":["Chemistry","physics","Astronomy"]}

for i in first_year:
    print("key:", i, "," , "value:", first_year[i])

key: Names , value: ['Salma', 'Islam', 'Mohamad', 'Nour']
key: Age , value: 17
key: subjects , value: ['Chemistry', 'physics', 'Astronomy']

In [109]:
first_year

{'Names': ['Salma', 'Islam', 'Mohamad', 'Nour'],
 'Age': 17,
 'subjects': ['Chemistry', 'physics', 'Astronomy']}

In [111]:
for i in first_year.values():
    print("value:" i)

['Salma', 'Islam', 'Mohamad', 'Nour']
17
['Chemistry', 'physics', 'Astronomy']

In [113]:
for i,j in first_year.items():
    print("key:",i, "," , "value:", first_year[i])

key: Names , value: ['Salma', 'Islam', 'Mohamad', 'Nour']
key: Age , value: 17
key: subjects , value: ['Chemistry', 'physics', 'Astronomy']

Looping over a Range

for i sequance in range(n):
    statments

range(n): Creates a sequensce of numers from 0 to n-1

range(a,b):  Creates a sequensce of numers from 0 to b-1

range(a,b,step):  Creates a sequensce of numers from 0 to b-1 and the step value 
 (By default each step equal to one.)

In [114]:
for i in range (2,20,2):
    print(i)

2
4
6
8
10
12
14
16
18

In [115]:
for i in range(len(days)):
    print("the index of day is {}, and the day is {}.".format(i,days[i]))

the index of day is 0, and the day is Saturday.
the index of day is 1, and the day is Sun.
the index of day is 2, and the day is Monday.
the index of day is 3, and the day is Tuesday.
the index of day is 4, and the day is wednes.
the index of day is 5, and the day is Thursday.
the index of day is 6, and the day is Friday.

Break and continue functions

In [117]:
for i in range(len(days)):
    print("Today is :{}".format(days[i]))
    if (days[i]=="Saturday"):
        print("This day :{} is my offday".format(days[i]))
        break

Today is :Saturday
This day :Saturday is my offday

In [118]:
for i in range(len(days)):
    print("Today is :{}".format(days[i]))
    if (days[i]=="Saturday"):
        print("day"+ days[i]+"is my offday")
        continue
    print(days[i]+" is a working day")

Today is :Saturday
daySaturdayis my offday
Today is :Sun
Sun is a working day
Today is :Monday
Monday is a working day
Today is :Tuesday
Tuesday is a working day
Today is :wednes
wednes is a working day
Today is :Thursday
Thursday is a working day
Today is :Friday
Friday is a working day

In [2]:
#make a code that find the max and min for the given list
X= [10,15,51,73,2,103,78,67,93,110,20,98,66,53,17,71,43,23,26,88,91,18,128,111,-2,9,81,31,45,62,78,54,23,123,45,76,44,32,44,35,67,23,45,12,32,87,90,4,5,-1,0,6,111,23,84,1]

In [8]:
max=0
for i in range(len(X)):
    if(X[i] > max):
        max=X[i]      
print(max)

128

In [5]:
line="*"
max_lenght=10

while len(line) <= max_lenght:
    print(line)
    line=line+"*"

*
**
***
****
*****
******
*******
********
*********
**********

2.Pandas

In [1]:
import pandas as pd

In [2]:
DrALaa_df= pd.read_csv("Dr. Alaa.csv")
grades_df=pd.read_excel("grades.xlsx")
DrALaa_df.head()

,Source_Name,DataRelease,RAJ2000,DEJ2000,GLON,GLAT,Conf_68_SemiMajor,Conf_68_SemiMinor,Conf_68_PosAng,Conf_95_SemiMajor,...,CLASS1,CLASS2,ASSOC1,ASSOC2,ASSOC_PROB_BAY,ASSOC_PROB_LR,RA_Counterpart,DEC_Counterpart,Unc_Counterpart,Flags
0,4FGL J0000.3-7355,1,0.0983,-73.9220,307.70898,-42.729538,0.032378,0.031453,-62.70,0.0525,...,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,0
1,4FGL J0000.5+0743,2,0.1375,7.7273,101.65648,-53.029457,0.094544,0.069999,-10.22,0.1533,...,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,0
2,4FGL J0001.2+4741,1,0.3126,47.6859,114.25020,-14.338059,0.036880,0.033180,-45.90,0.0598,...,bcu,NaN,B3 2358+474,NaN,0.996097,0.938563,0.329341,47.700201,8.400000e-07,0
3,4FGL J0001.2-0747,1,0.3151,-7.7971,89.03272,-67.305010,0.018440,0.017577,64.10,0.0299,...,bll,NaN,PMN J0001-0746,NaN,0.997014,0.932932,0.325104,-7.774145,1.800000e-07,0
4,4FGL J0001.5+2113,1,0.3815,21.2183,107.64935,-40.167652,0.026026,0.023991,-60.52,0.0422,...,fsrq,NaN,TXS 2358+209,NaN,0.998049,0.958182,0.384877,21.226743,3.400000e-07,0

In [12]:
RA=DrALaa_df['RAJ2000']
Dec=DrALaa_df['DEJ2000']
flux=DrALaa_df['Energy_Flux100']
print(RA)

0         0.0983
1         0.1375
2         0.3126
3         0.3151
4         0.3815
          ...
5783    359.8167
5784    359.8329
5785    359.8357
5786    359.8390
5787    359.9816
Name: RAJ2000, Length: 5788, dtype: float64

In [13]:
DrALaa_df.describe()

,DataRelease,RAJ2000,DEJ2000,GLON,GLAT,Conf_68_SemiMajor,Conf_68_SemiMinor,Conf_68_PosAng,Conf_95_SemiMajor,Conf_95_SemiMinor,...,Flux_Peak,Unc_Flux_Peak,Time_Peak,Peak_Interval,ASSOC_PROB_BAY,ASSOC_PROB_LR,RA_Counterpart,DEC_Counterpart,Unc_Counterpart,Flags
count,5788.000000,5788.000000,5788.000000,5788.000000,5788.000000,5712.000000,5712.000000,5712.000000,5712.000000,5712.000000,...,1.525000e+03,1.525000e+03,1.525000e+03,1.525000e+03,5526.000000,5713.000000,4121.000000,4121.000000,4.124000e+03,5788.000000
mean,1.124914,190.170195,-3.899549,183.464316,0.910269,0.053122,0.041443,-1.273065,0.086135,0.067199,...,6.574294e-08,3.713070e-09,3.918366e+08,3.153032e+07,0.661815,0.460059,181.832253,0.851464,9.505287e-03,136.991189
std,0.330650,99.423257,40.235018,112.085142,36.324807,0.048416,0.030118,52.804902,0.078506,0.048835,...,2.173708e-07,2.690017e-09,9.518910e+07,7.662945e+04,0.454322,0.467681,101.746037,39.957524,1.022462e-01,652.234971
min,1.000000,0.098300,-87.686100,0.042404,-87.969360,0.004502,0.004440,-90.000000,0.007300,0.007200,...,9.913227e-10,2.823079e-10,2.552237e+08,3.133258e+07,0.000000,0.000000,0.035059,-86.313225,3.502591e-08,0.000000
25%,1.000000,108.776325,-36.472800,82.315722,-22.166975,0.025455,0.022757,-48.582500,0.041275,0.036900,...,1.376703e-08,2.213178e-09,3.182300e+08,3.156000e+07,0.000000,0.000000,95.541664,-30.464916,1.500000e-07,0.000000
50%,1.000000,202.320500,-6.757950,182.689875,0.023966,0.040704,0.034475,-1.945000,0.066000,0.055900,...,2.504494e-08,3.258452e-09,3.813500e+08,3.156000e+07,0.987107,0.000000,185.382044,0.574396,5.711515e-07,0.000000
75%,1.000000,271.620575,28.278275,287.455488,25.887804,0.065435,0.051204,44.800000,0.106100,0.083025,...,5.242213e-08,4.420188e-09,4.760300e+08,3.156000e+07,0.998661,0.943831,267.136835,33.123030,1.700000e-05,1.000000
max,2.000000,359.981600,88.737600,359.992160,88.682230,0.783552,0.391437,90.000000,1.270500,0.634700,...,5.146125e-06,3.513400e-08,5.391500e+08,3.156000e+07,1.000000,1.000000,359.897888,88.737587,2.500000e+00,6160.000000

In [13]:
DrALaa_df.drop(['GLAT'],axis=1).head()

,Source_Name,DataRelease,RAJ2000,DEJ2000,GLON,Conf_68_SemiMajor,Conf_68_SemiMinor,Conf_68_PosAng,Conf_95_SemiMajor,Conf_95_SemiMinor,...,CLASS1,CLASS2,ASSOC1,ASSOC2,ASSOC_PROB_BAY,ASSOC_PROB_LR,RA_Counterpart,DEC_Counterpart,Unc_Counterpart,Flags
0,4FGL J0000.3-7355,1,0.0983,-73.9220,307.70898,0.032378,0.031453,-62.70,0.0525,0.0510,...,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,0
1,4FGL J0000.5+0743,2,0.1375,7.7273,101.65648,0.094544,0.069999,-10.22,0.1533,0.1135,...,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,0
2,4FGL J0001.2+4741,1,0.3126,47.6859,114.25020,0.036880,0.033180,-45.90,0.0598,0.0538,...,bcu,NaN,B3 2358+474,NaN,0.996097,0.938563,0.329341,47.700201,8.400000e-07,0
3,4FGL J0001.2-0747,1,0.3151,-7.7971,89.03272,0.018440,0.017577,64.10,0.0299,0.0285,...,bll,NaN,PMN J0001-0746,NaN,0.997014,0.932932,0.325104,-7.774145,1.800000e-07,0
4,4FGL J0001.5+2113,1,0.3815,21.2183,107.64935,0.026026,0.023991,-60.52,0.0422,0.0389,...,fsrq,NaN,TXS 2358+209,NaN,0.998049,0.958182,0.384877,21.226743,3.400000e-07,0

In [14]:
DrALaa_df['Energy_Flux100'].mean()

1.4576408996677598e-11

In [15]:
DrALaa_df.groupby(['DataRelease']).mean()

,RAJ2000,DEJ2000,GLON,GLAT,Conf_68_SemiMajor,Conf_68_SemiMinor,Conf_68_PosAng,Conf_95_SemiMajor,Conf_95_SemiMinor,Conf_95_PosAng,...,Flux_Peak,Unc_Flux_Peak,Time_Peak,Peak_Interval,ASSOC_PROB_BAY,ASSOC_PROB_LR,RA_Counterpart,DEC_Counterpart,Unc_Counterpart,Flags
DataRelease,,,,,,,,,,,,,,,,,,,,,
1,188.741392,-3.391229,183.293371,1.165441,0.048715,0.038532,-1.399844,0.078990,0.062478,-1.399844,...,6.746043e-08,3.711009e-09,3.880245e+08,3.152921e+07,0.700354,0.487425,181.305261,0.973597,0.010136,141.511945
2,200.179720,-7.460599,184.661878,-0.877349,0.083532,0.061532,-0.398243,0.135444,0.099771,-0.398243,...,3.004351e-08,3.755902e-09,4.710738e+08,3.155350e+07,0.405793,0.271186,187.636849,-0.493786,0.002548,105.320885

In [16]:
DrALaa_df[DrALaa_df['Energy_Flux100']>0.00000000006618022].groupby(['DataRelease']).mean()

,RAJ2000,DEJ2000,GLON,GLAT,Conf_68_SemiMajor,Conf_68_SemiMinor,Conf_68_PosAng,Conf_95_SemiMajor,Conf_95_SemiMinor,Conf_95_PosAng,...,Flux_Peak,Unc_Flux_Peak,Time_Peak,Peak_Interval,ASSOC_PROB_BAY,ASSOC_PROB_LR,RA_Counterpart,DEC_Counterpart,Unc_Counterpart,Flags
DataRelease,,,,,,,,,,,,,,,,,,,,,
1,209.391714,-6.864119,168.483417,2.287959,0.008069,0.007748,7.968037,0.013084,0.012563,7.968037,...,6.574900e-07,9.905319e-09,4.011534e+08,3.153687e+07,0.949842,0.595386,207.743192,-4.097457,1.524953e-01,82.027211
2,342.504900,-12.848500,53.584927,-58.228350,0.008387,0.008264,89.190000,0.013600,0.013400,89.190000,...,5.975825e-07,1.758154e-08,5.391500e+08,3.156000e+07,0.999430,0.990109,342.498383,-12.854673,1.100000e-07,260.000000

Plotting using Pandas

In [ ]:
pd.value_counts(DrALaa_df['Energy_Flux100']).plot.bar()

Creating CSV files

In [14]:
import csv
with open("mystar.csv", "w", newline="") as f:
    thewriter=csv.writer(f)
    thewriter.writerow(["col1","col2","col3"])
    thewriter.writerow(["RA", "Dec", "flux"])
    for i in range(1,100):
        thewriter.writerow([RA[i], Dec[i], flux[i]])